name: Build Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: Change to Build Branch
              run: |
                  git switch -c build

            - name: Build Templex
              run: |
                  cd templex  
                  yarn install
                  yarn build

            - name: Build Pages
              run: |
                  node ./templex/dist/main.js build
                  git config --global user.name "build@actions"
                  git config --global user.email "build@actions"
                  git add .
                  git commit -m "build" || true
                  git push -f --set-upstream origin build

            - name: Copy to other Branch
              run: |
                  git config --global user.name "build@actions"
                  git config --global user.email "build@actions"
                  git checkout --orphan gh-pages
                  git reset --hard && rm -rf ./templex
                  git checkout build -- public
                  mv public/* . && rm -rf ./public
                  git add .
                  # Force the build to succeed, even if no files were changed
                  git commit -m "deploy" || true
                  git push -f --set-upstream origin gh-pages
