name: Build Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: Build Templex
              run: |
                  cd templex  
                  yarn install
                  yarn build

            - name: Build Pages
              run: |
                  tree
                  node ./templex/dist/main.js build

            - name: Copy to other Branch
              run: |
                  git config --global user.name "templex@Rayy"
                  git config --global user.email "templex@Rayy"
                  git checkout --orphan gh-pages
                  git reset --hard && rm -rf ./templex
                  git checkout main -- public
                  mv public/* . && rm -rf ./public
                  tree
                  # Force the build to succeed, even if no files were changed
                  git commit -m "deploy" || true
                  git push --set-upstream origin gh-pages
