name: Build Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Build Templex
              run: |
                  cd templex  
                  yarn install
                  yarn build

            - name: Build Pages
              run: |
                  cd ..
                  yarn start build

            - name: Commit to the repo
              run: |
                  git config --global user.name "templex@Rayy"
                  git config --global user.email "templex@Rayy"
                  git add .
                  # Force the build to succeed, even if no files were changed
                  git commit -m 'Update generated files' || true
                  git push
